//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.02 at 06:31:42 PM IST 
//

package com.athiththan.soap.devservice.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.athiththan.devservice package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema
     * derived classes for package: com.athiththan.devservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDeveloper }
     * 
     */
    public GetDeveloper createGetDeveloper() {
        return new GetDeveloper();
    }

    /**
     * Create an instance of {@link GetDeveloperResponse }
     * 
     */
    public GetDeveloperResponse createGetDeveloperResponse() {
        return new GetDeveloperResponse();
    }

    /**
     * Create an instance of {@link Developer }
     * 
     */
    public Developer createDeveloper() {
        return new Developer();
    }

}
